tap "buo/cask-upgrade"
tap "federico-terzi/espanso"
tap "felixkratz/formulae"
tap "homebrew/autoupdate"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers", "https://mirrors.tuna.tsinghua.edu.cn/git/homebrew/homebrew-cask-drivers.git"
tap "homebrew/cask-fonts", "https://mirrors.tuna.tsinghua.edu.cn/git/homebrew/homebrew-cask-fonts.git"
tap "homebrew/cask-versions", "https://mirrors.tuna.tsinghua.edu.cn/git/homebrew/homebrew-cask-versions.git"
tap "homebrew/core"
tap "homebrew/services"
tap "koekeishiya/formulae"
tap "zegervdv/zathura"
brew "glib"
brew "readline"
brew "python@3.9"
brew "aria2"
brew "gcc"
brew "libevent"
brew "atool"
brew "autojump"
brew "ccat"
brew "jansson"
brew "clamav"
brew "curl"
brew "exa"
brew "jasper"
brew "figlet"
brew "frpc", restart_service: true
brew "fzf"
brew "git"
brew "libgcrypt"
brew "lua"
brew "go"
brew "handbrake"
brew "node", link: false
brew "hexo"
brew "hugo"
brew "imagemagick"
brew "iperf3"
brew "ipython"
brew "isync"
brew "lastpass-cli"
brew "lazygit"
brew "libconfig"
brew "libressl"
brew "libsecret"
brew "mackup"
brew "make"
brew "mas"
brew "msmtp"
brew "mysql"
brew "neofetch"
brew "neomutt"
brew "neovim"
brew "nvm"
brew "octave"
brew "openjdk"
brew "openssh"
brew "p7zip"
brew "pandoc"
brew "tree"
brew "pass"
brew "ranger"
brew "redis"
brew "rust"
brew "sbcl"
brew "speedtest-cli"
brew "subversion"
brew "syncthing", restart_service: true
brew "texlive"
brew "the_silver_searcher"
brew "tmux"
brew "translate-shell"
brew "vcpkg"
brew "w3m"
brew "wget"
brew "wireguard-tools"
brew "xray"
brew "zoxide"
brew "zsh"
brew "zsh-syntax-highlighting"
brew "zegervdv/zathura/girara", args: ["HEAD"]
brew "zegervdv/zathura/zathura", args: ["HEAD"]
brew "zegervdv/zathura/zathura-pdf-poppler"
cask "aldente"
cask "amethyst"
cask "android-platform-tools"
cask "apparency"
cask "betterzip"
cask "bob"
cask "calibre"
cask "clash-for-windows"
cask "clashx-pro"
cask "clean-me"
cask "cryptomator"
cask "darktable"
cask "deepl"
cask "docker"
cask "firefox"
cask "font-fira-code"
cask "font-fira-code-nerd-font"
cask "font-fontawesome"
cask "font-hack-nerd-font"
cask "free-download-manager"
cask "goldendict"
cask "google-backup-and-sync"
cask "google-chrome"
cask "google-earth-pro"
cask "gpg-suite-no-mail"
cask "hammerspoon"
cask "hiddenbar"
cask "hyper"
cask "iina"
cask "imageoptim"
cask "inkscape"
cask "iterm2"
cask "jetbrains-gateway"
cask "joplin"
cask "karabiner-elements"
cask "keepassxc"
cask "keka"
cask "keybase"
cask "keycastr"
cask "keymanager"
cask "koodo-reader"
cask "latexit"
cask "lulu"
cask "macvim"
cask "maczip"
cask "microsoft-auto-update"
cask "microsoft-remote-desktop"
cask "microsoft-teams"
cask "motrix"
cask "neteasemusic"
cask "netnewswire"
cask "nextcloud"
cask "obs"
cask "obsidian"
cask "omnidisksweeper"
cask "onedrive"
cask "pycharm"
cask "qlcolorcode"
cask "qlimagesize"
cask "qlmarkdown"
cask "qlstephen"
cask "qlvideo"
cask "quicklook-csv"
cask "quicklook-json"
cask "quicklookase"
cask "r"
cask "raycast"
cask "rustdesk"
cask "secretive"
cask "signal"
cask "skim"
cask "spotify"
cask "squirrel"
cask "stats"
cask "steam"
cask "sublime-text"
cask "suspicious-package"
cask "tableau"
cask "tableau-prep"
cask "telegram-desktop"
cask "tencent-meeting"
cask "thunderbird"
cask "toggl-track"
cask "typora"
cask "ubersicht"
cask "upic"
cask "virtualbox"
cask "visual-studio-code"
cask "vscodium"
cask "warp"
cask "webpquicklook"
cask "zotero"
mas "AdGuard for Safari", id: 1440147259
mas "CAJ云阅读", id: 1121965993
mas "CHM Viewer Star", id: 650683226
mas "Cubox", id: 1113361350
mas "Cubox for Safari", id: 1550721541
mas "Grammarly for Safari", id: 1462114288
mas "iMovie", id: 408981434
mas "Insomniac", id: 1434172648
mas "iRightMouse", id: 1497428978
mas "iShot", id: 1485844094
mas "Keynote", id: 409183694
mas "MarginNote 3", id: 1423522373
mas "Mathpix Snipping Tool", id: 1349670778
mas "Numbers", id: 409203825
mas "Octotree", id: 1457450145
mas "Pages", id: 409201541
mas "QQ", id: 451108668
mas "Save to Pocket", id: 1477385213
mas "SimpleLogin", id: 1494051017
mas "Tab Space", id: 1473726602
mas "Table Tool", id: 1122008420
mas "Tencent Lemon Lite", id: 1449962996
mas "Termius", id: 1176074088
mas "Vimari", id: 1480933944
mas "WeChat", id: 836500024
mas "WidsMob Denoise", id: 1393718073
mas "Wind Stock", id: 1271308896
mas "同花顺", id: 1247341465
mas "每日英语听力", id: 734383760
